server:
  port: 8082
spring:
  application:
    name: seller-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#project-service.ribbon.listOfServers=localhost:8082