server:
  port: 8081
spring:
  application:
    name: product-service
eureka:
  client:
    healthcheck:
        enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

